// Custom architectural plugins
import pluginCodeFlow from "@boring-stack-pkg/eslint-plugin-code-flow";
import pluginCommentHygiene from "@boring-stack-pkg/eslint-plugin-comment-hygiene";
import pluginEnvAccess from "@boring-stack-pkg/eslint-plugin-env-access";
import pluginI18nKeys from "@boring-stack-pkg/eslint-plugin-i18n-keys";
import pluginModuleBoundaries from "@boring-stack-pkg/eslint-plugin-module-boundaries";
import pluginRCA from "@boring-stack-pkg/eslint-plugin-react-component-architecture";
import pluginResourceArch from "@boring-stack-pkg/eslint-plugin-resource-architecture";
import pluginStructuredLogging from "@boring-stack-pkg/eslint-plugin-structured-logging";
import pluginTanstackQueryCache from "@boring-stack-pkg/eslint-plugin-tanstack-query-cache";
import pluginTestConventions from "@boring-stack-pkg/eslint-plugin-test-conventions";
import pluginEslintComments from "@eslint-community/eslint-plugin-eslint-comments";
import pluginJs from "@eslint/js";
import pluginJson from "@eslint/json";
import configPrettier from "eslint-config-prettier";
import pluginImport from "eslint-plugin-import";
import pluginJsxA11y from "eslint-plugin-jsx-a11y";
import pluginPromise from "eslint-plugin-promise";
import pluginReact from "eslint-plugin-react";
import pluginReactHooks from "eslint-plugin-react-hooks";
import pluginReactRefresh from "eslint-plugin-react-refresh";
import pluginSonarjs from "eslint-plugin-sonarjs";
import pluginUnicorn from "eslint-plugin-unicorn";
import tseslint from "typescript-eslint";

// AI-first linting (mirror of the API app's philosophy): every rule that
// catches a likely agent mistake is an `error`, not a `warn`. Agents iterate
// by running `bun run check` and reading failures; warnings are easy to miss in
// that loop, so we collapse the severity space to error/off only.
//
// Hard denials:
//   - `any` (use `unknown` + narrow)
//   - `as` casting (only `as const` permitted)
//   - non-null `!` assertions
//   - floating / misused promises
//   - hardcoded user-facing strings in JSX (handled by react-component-architecture)
//   - className= ternaries / template literals (handled by react-component-architecture)
//   - useState/useEffect inside *.tsx (must live in *.hooks.ts)

export default tseslint.config(
  {
    ignores: [
      "dist",
      "node_modules",
      "storybook-static",
      "playwright-report",
      "test-results",
      "coverage",
      ".eslintcache",
      ".lighthouseci",
      "src/components/ui/**", // shadcn primitives — owned by shadcn conventions
      "src/lib/api/schema.d.ts", // generated by `bun run generate:api`
      "src/lib/acl/acl.types.generated.ts", // generated by the API app's `bun run generate:acl-types`
      /*
       * Fixtures intentionally contain forbidden patterns to exercise
       * lint-meta rules. They must not be scanned by ESLint itself.
       */
      "tests/lint-meta/fixtures/**",
      "**/*.d.ts", // ambient declarations don't need our prefix rules
      "*.config.{js,mjs,cjs}",
      "vite.config.ts",
      "vitest.config.ts",
      "playwright.config.ts",
      // .github/workflows/*.yml: format-rules (permissions block + pinned SHAs)
      // are enforced by `bun run lint:meta`, which runs in `bun run check`. ESLint
      // doesn't natively lint YAML structure.
      ".github/workflows/*.{yml,yaml}",
      // bun.lock: huge, auto-generated, never hand-edited
      "bun.lock"
    ]
  },

  // ---------------------------------------------------------------------------
  // JSON / JSONC config files — @eslint/json provides a JSON-aware language
  // so ESLint can validate structure (duplicate keys, empty keys, trailing
  // commas in strict JSON, etc.) directly in editor + CI. Our
  // `package-json-exact-deps` rule remains in `bun run lint:meta` because it
  // needs JSON-AST node types our React-component plugin doesn't ship.
  // ---------------------------------------------------------------------------
  {
    files: ["**/*.json"],
    ignores: [
      "node_modules/**",
      "dist/**",
      "storybook-static/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      "package-lock.json",
      // Lock files for size + lack of hand-editing
      "**/pnpm-lock.json"
    ],
    language: "json/json",
    plugins: { json: pluginJson },
    rules: {
      "json/no-duplicate-keys": "error",
      "json/no-empty-keys": "error",
      "json/no-unsafe-values": "error",
      "json/no-unnormalized-keys": "error",
      "json/top-level-interop": "error"
    }
  },

  // JSONC (JSON with comments) — tsconfig.json, .vscode/settings.json
  {
    files: [
      "tsconfig.json",
      "tsconfig.*.json",
      ".vscode/**/*.json",
      "**/*.jsonc"
    ],
    language: "json/jsonc",
    plugins: { json: pluginJson },
    rules: {
      "json/no-duplicate-keys": "error",
      "json/no-empty-keys": "error"
    }
  },

  // ---------------------------------------------------------------------------
  // Base config — applies to all .ts / .tsx in src, tests, e2e, scripts
  // ---------------------------------------------------------------------------
  {
    files: [
      "src/**/*.{ts,tsx}",
      "tests/**/*.{ts,tsx}",
      "e2e/**/*.ts",
      "scripts/**/*.ts",
      ".storybook/**/*.{ts,tsx}"
    ],
    extends: [
      pluginJs.configs.recommended,
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
      configPrettier
    ],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: 2023,
        sourceType: "module",
        ecmaFeatures: { jsx: true },
        project: "./tsconfig.json",
        tsconfigRootDir: import.meta.dirname
      },
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        console: "readonly",
        // Vite client types
        ImportMeta: "readonly"
      }
    },
    settings: {
      react: { version: "19.2" },
      "import/resolver": {
        typescript: { project: "./tsconfig.json" }
      }
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      react: pluginReact,
      "react-hooks": pluginReactHooks,
      "react-refresh": pluginReactRefresh,
      "jsx-a11y": pluginJsxA11y,
      import: pluginImport,
      promise: pluginPromise,
      sonarjs: pluginSonarjs,
      unicorn: pluginUnicorn,
      "code-flow": pluginCodeFlow,
      "comment-hygiene": pluginCommentHygiene,
      "env-access": pluginEnvAccess,
      "eslint-comments": pluginEslintComments,
      "module-boundaries": pluginModuleBoundaries,
      "resource-architecture": pluginResourceArch,
      "structured-logging": pluginStructuredLogging,
      "test-conventions": pluginTestConventions,
      "react-component-architecture": pluginRCA,
      "i18n-keys": pluginI18nKeys
    },
    rules: {
      // -----------------------------------------------------------------------
      // Stylistic structure — no bare statements without braces, mandatory
      // blank-line breathing room around block-likes + declarations + returns.
      // The body of an `if`, `for`, `while`, `do` is ALWAYS a block, never
      // a single statement on the same line.
      // -----------------------------------------------------------------------
      curly: ["error", "all"],
      "nonblock-statement-body-position": ["error", "below"],
      "code-flow/prefer-early-return": "error",
      "code-flow/no-bare-date-now": [
        "error",
        { allowedPaths: ["src/lib/time/"] }
      ],
      "comment-hygiene/no-historical-comments": "error",
      "comment-hygiene/no-narration-comments": "error",
      "comment-hygiene/no-pr-reference-comments": "error",
      /*
       * Defense-in-depth ban on inline lint suppression. lint-meta.ts
       * enforces the same ban at merge gate via source-text scan; this
       * rule adds IDE-level feedback while typing.
       */
      "eslint-comments/no-use": ["error", { allow: [] }],
      /*
       * Multi-line comment blocks must use a single /* ... *\/ block,
       * not 3+ consecutive // lines. Cleaner diffs, JSDoc parity.
       */
      "multiline-comment-style": ["error", "starred-block"],

      /*
       * One canonical wall clock. Use now() from src/lib/time/now.ts so
       * tests can mock a single site and the format can change in one
       * place. The util's own file is excepted by a scoped override.
       *
       * Bare `new Date().toISOString()` only — i.e. no constructor
       * arguments. `new Date(x).toISOString()` is intentional (often
       * expiry / TTL math) and stays in place.
       */
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.type='MemberExpression'][callee.property.name='toISOString'][callee.object.type='NewExpression'][callee.object.callee.name='Date'][callee.object.arguments.length=0]",
          message:
            "Use now() from @/lib/time/now instead of new Date().toISOString()."
        }
      ],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "consistent-return": "error",
      "no-implicit-coercion": [
        "error",
        {
          boolean: true,
          number: true,
          string: true,
          disallowTemplateShorthand: true
        }
      ],
      "default-case": "error",
      "default-case-last": "error",
      "no-useless-concat": "error",
      "prefer-template": "error",
      "no-nested-ternary": "error",
      "no-unneeded-ternary": "error",
      "no-lonely-if": "error",
      "no-useless-rename": "error",
      "object-shorthand": ["error", "always"],
      "prefer-object-spread": "error",
      "no-useless-return": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "separate-type-imports" }
      ],
      "padding-line-between-statements": [
        "error",
        // Rules are evaluated in order; last match wins. Put the broader
        // rule first and exceptions after.
        //
        // Imports first: separate the cluster from code, but allow tight
        // packing inside the cluster (and let Prettier's import-sorter
        // group them by category — those gaps don't count as "missing").
        { blankLine: "always", prev: "import", next: "*" },
        { blankLine: "any", prev: "import", next: "import" },
        // Always blank line before a return.
        { blankLine: "always", prev: "*", next: "return" },
        // Always blank line before a throw (terminal statements deserve
        // visual separation from the work that built up to them).
        { blankLine: "always", prev: "*", next: "throw" },
        // Always blank line after a group of declarations (let/const/var)
        // unless the next statement is another declaration.
        { blankLine: "always", prev: ["const", "let", "var"], next: "*" },
        {
          blankLine: "any",
          prev: ["const", "let", "var"],
          next: ["const", "let", "var"]
        },
        // Block-likes (if/for/while/try/switch/etc.) are separated from
        // surrounding code by blank lines on both sides.
        { blankLine: "always", prev: "block-like", next: "*" },
        { blankLine: "always", prev: "*", next: "block-like" }
      ],

      // -----------------------------------------------------------------------
      // Hard bans — things an AI agent must never write
      // -----------------------------------------------------------------------
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/consistent-type-assertions": [
        "error",
        {
          assertionStyle: "as",
          objectLiteralTypeAssertions: "never"
        }
      ],
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",

      "i18n-keys/static-translation-key-exists": [
        "error",
        { dictionary: "src/lib/i18n/locales/en/common.json" }
      ],

      // -----------------------------------------------------------------------
      // Async correctness
      // -----------------------------------------------------------------------
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/return-await": ["error", "in-try-catch"],

      // -----------------------------------------------------------------------
      // Type safety
      // -----------------------------------------------------------------------
      "@typescript-eslint/strict-boolean-expressions": [
        "error",
        {
          allowNullableObject: true,
          allowString: false,
          allowNumber: false,
          allowNullableBoolean: true
        }
      ],
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/no-unsafe-enum-comparison": "error",
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }
      ],

      // -----------------------------------------------------------------------
      // Naming
      // -----------------------------------------------------------------------
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "interface",
          format: ["PascalCase"],
          prefix: ["I"]
        },
        {
          selector: "typeAlias",
          format: ["PascalCase"]
        },
        {
          selector: "variable",
          modifiers: ["const", "global"],
          format: ["UPPER_CASE", "PascalCase", "camelCase"]
        },
        {
          selector: "function",
          format: ["camelCase", "PascalCase"]
        }
      ],

      // -----------------------------------------------------------------------
      // React
      // -----------------------------------------------------------------------
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "react/jsx-no-bind": [
        "error",
        {
          allowArrowFunctions: false,
          allowBind: false,
          allowFunctions: false,
          ignoreRefs: true,
          ignoreDOMComponents: false
        }
      ],
      "react/jsx-uses-react": "off",
      "react/jsx-uses-vars": "error",
      "react/jsx-key": "error",
      "react/no-array-index-key": "error",
      "react/self-closing-comp": "error",
      "react/jsx-pascal-case": "error",
      "react/no-unknown-property": "error",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "error",
      "react-refresh/only-export-components": [
        "error",
        { allowConstantExport: true }
      ],

      // -----------------------------------------------------------------------
      // Accessibility (AGENTS.md a11y section)
      // -----------------------------------------------------------------------
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-has-content": "error",
      "jsx-a11y/anchor-is-valid": "error",
      "jsx-a11y/aria-props": "error",
      "jsx-a11y/aria-role": "error",
      "jsx-a11y/aria-unsupported-elements": "error",
      "jsx-a11y/click-events-have-key-events": "error",
      "jsx-a11y/heading-has-content": "error",
      "jsx-a11y/img-redundant-alt": "error",
      "jsx-a11y/interactive-supports-focus": "error",
      "jsx-a11y/label-has-associated-control": "error",
      "jsx-a11y/no-noninteractive-element-interactions": "error",
      "jsx-a11y/no-redundant-roles": "error",
      "jsx-a11y/no-static-element-interactions": "error",
      "jsx-a11y/role-has-required-aria-props": "error",
      "jsx-a11y/role-supports-aria-props": "error",

      // -----------------------------------------------------------------------
      // Import hygiene
      // -----------------------------------------------------------------------
      "import/no-duplicates": "error",
      "import/no-self-import": "error",
      "import/no-cycle": "error",
      "import/no-useless-path-segments": "error",

      // -----------------------------------------------------------------------
      // Promise + general quality
      // -----------------------------------------------------------------------
      "promise/no-return-wrap": "error",
      "promise/param-names": "error",
      "promise/catch-or-return": "error",
      "sonarjs/cognitive-complexity": ["error", 20],
      "sonarjs/no-duplicate-string": "off",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/no-useless-undefined": "off",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/filename-case": [
        "error",
        {
          cases: { camelCase: true, pascalCase: true, kebabCase: true }
        }
      ],

      // -----------------------------------------------------------------------
      // Custom architectural plugins
      // -----------------------------------------------------------------------
      "structured-logging/require-event-field": "error",
      "structured-logging/mask-pii-fields": "error",
      "structured-logging/no-error-stringify": "error",
      "structured-logging/typed-event-names": [
        "error",
        {
          eventNamesModule: "src/lib/logger/logger.events.ts",
          eventNamesExport: "LOG_EVENTS"
        }
      ],
      "env-access/no-direct-process-env": "error",
      "module-boundaries/single-semantic-module": [
        "error",
        {
          allow: []
        }
      ],
      "test-conventions/no-focused-tests": "error",

      // No `console.*` in source (logger.* required) — provided by core ESLint
      "no-console": "error",
      "no-restricted-globals": [
        "error",
        {
          name: "fetch",
          message:
            "Use the typed OpenAPI client (`@/lib/api/client`) instead of raw fetch."
        }
      ],

      // -----------------------------------------------------------------------
      // React Component Architecture (15th custom plugin)
      // -----------------------------------------------------------------------
      "react-component-architecture/classnames-required": "error",
      "react-component-architecture/classnames-import-name": "error",
      "react-component-architecture/no-dark-mode-classes": "error",
      "react-component-architecture/no-inline-jsx-functions": "error",
      "react-component-architecture/interface-prefix-i": "error",
      "react-component-architecture/forwardref-display-name": "error",
      "react-component-architecture/stories-require-default-export": "error",
      "react-component-architecture/react-import-named": "error",
      "react-component-architecture/index-must-reexport-default": "error",
      "react-component-architecture/component-folder-structure": [
        "error",
        {
          // We use .test.tsx (RTL needs JSX); plugin default is .test.ts.
          requiredSiblings: [
            "<Name>.hooks.ts",
            "<Name>.types.ts",
            "<Name>.stories.tsx",
            "<Name>.test.tsx",
            "index.ts"
          ]
        }
      ],
      "react-component-architecture/no-state-in-component-body": "error",
      "react-component-architecture/no-jsx-computation": "error",
      "react-component-architecture/props-must-be-visual": "error",
      "react-component-architecture/no-untranslated-jsx-text": "error",
      // v0.2.0 architectural rules
      "react-component-architecture/query-keys-must-be-constant": "error",
      "react-component-architecture/max-hooks-per-file": [
        "error",
        { threshold: 4 }
      ],
      "react-component-architecture/no-cross-feature-imports": [
        "error",
        {
          // Allow type-only imports across features (no runtime coupling)
          allowSiblingTypes: true,
          /*
           * `dashboard.hooks` legitimately consumes the auth `useMe`/
           * `useLogout` queries because they're the canonical auth API.
           * Other auth↔feature crossings should still fail.
           */
          allowList: [
            ["dashboard", "auth"],
            /*
             * `notifications` gates SSE on the authenticated user;
             * `useMe` is the canonical auth handle.
             */
            ["notifications", "auth"],
            /*
             * `accounts` reads memberships + active account id from the
             * `/me` response and invalidates its cache after a switch.
             * The `useMe` query is the canonical auth handle.
             */
            ["accounts", "auth"],
            /*
             * `billing` gates checkout/portal on owner role and subscription
             * state from the canonical `/me` response.
             */
            ["billing", "auth"]
          ]
        }
      ]
    }
  },

  // Rules `package-json-exact-deps` and `github-actions-permissions` are
  // enforced via `bun run lint:meta` (scripts/lint-meta/cli.ts) which runs in
  // `bun run check`. ESLint's JS-only parser can't read .json / .yml directly.

  // ---------------------------------------------------------------------------
  // App-shell scaffold (providers, router, NotFoundPage, etc.) — exempted
  // from component-folder-structure + state-in-body because these are
  // infrastructure wrappers, not domain components.
  // ---------------------------------------------------------------------------
  {
    files: [
      "src/app/**/*.tsx",
      "src/components/global/**/*.tsx",
      "src/lib/**/*.tsx"
    ],
    rules: {
      "react-component-architecture/component-folder-structure": "off",
      "react-component-architecture/no-state-in-component-body": "off",
      /*
       * App-shell wrappers wire together router config, error-boundary
       * state, and provider trees — mixing concerns is the entire point of
       * the file. `src/lib/**` ships infra primitives (a typed `<Can>` over
       * @casl/react, a context provider, etc.) that aren't feature
       * components either; the folder-anatomy rule would force junk
       * siblings that mean nothing.
       */
      "module-boundaries/single-semantic-module": "off"
    }
  },

  // ---------------------------------------------------------------------------
  // *.tsx components — must NOT import data/router/state directly
  // (state lives in *.hooks.ts, queries live in *.queries.ts)
  // ---------------------------------------------------------------------------
  {
    files: ["src/**/*.tsx"],
    ignores: [
      "src/**/*.stories.tsx",
      "src/**/*.test.tsx",
      "src/app/**/*.tsx",
      "src/**/*.routes.tsx",
      "src/components/ui/**"
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@tanstack/react-query",
              message:
                "Server-state hooks belong in *.queries.ts and are consumed from *.hooks.ts. Components only read the result via props or hooks."
            },
            {
              name: "zustand",
              message:
                "Zustand stores belong in *.store.ts. Components consume them via *.hooks.ts."
            },
            {
              name: "axios",
              message: "Use @/lib/api/client (typed fetch wrapper) instead."
            }
          ],
          patterns: [
            {
              group: ["**/*.queries", "**/*.store"],
              message:
                "Components must not import queries or stores directly. Compose them in *.hooks.ts and pass values down."
            }
          ]
        }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // *.schemas.ts — zod only
  // ---------------------------------------------------------------------------
  {
    files: ["src/**/*.schemas.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "react",
                "react-*",
                "@tanstack/*",
                "zustand",
                "@/components/*",
                "@/features/*",
                "@/hooks/*",
                "@/lib/api/*"
              ],
              message: "Schema files may only import `zod` and shared types."
            }
          ]
        }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // *.constants.ts — literals only
  // ---------------------------------------------------------------------------
  {
    files: ["src/**/*.constants.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/*"],
              message:
                "Constants files contain only literal values — no imports."
            }
          ]
        }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // *.queries.ts — TanStack Query hooks layer
  // ---------------------------------------------------------------------------
  {
    files: ["src/**/*.queries.ts"],
    plugins: {
      "tanstack-query-cache": pluginTanstackQueryCache
    },
    rules: {
      "tanstack-query-cache/prefix-query-key-must-use-set-queries-data":
        "error",
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/components/*", "react-dom"],
              message:
                "Queries are a pure data layer — no JSX, no component imports."
            }
          ]
        }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // Sub-components inside a `*Page/` folder (e.g. StatsSection.tsx inside
  // DashboardPage/) are private implementation details of the page — they
  // don't get the full hooks/types/stories/test folder ceremony reserved for
  // top-level components. The main `*Page.tsx` itself still has to satisfy
  // the structure rule.
  // ---------------------------------------------------------------------------
  {
    files: ["src/features/**/components/*Page/*.tsx"],
    ignores: [
      "src/features/**/components/*Page/*Page.tsx",
      "**/*.test.tsx",
      "**/*.stories.tsx"
    ],
    rules: {
      "react-component-architecture/component-folder-structure": "off"
    }
  },

  // ---------------------------------------------------------------------------
  // *.hooks.ts — the file's main export is one or more hooks, but they often
  // share local helper functions. Allow that specific pair (and the type
  // pairings inherited from the base config).
  // ---------------------------------------------------------------------------
  {
    files: ["src/**/*.hooks.ts"],
    rules: {
      "module-boundaries/single-semantic-module": [
        "error",
        {
          allow: [
            ["type", "hook"],
            ["function", "hook"],
            ["type", "function", "hook"]
          ]
        }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // *.store.ts — zustand store modules. The canonical zustand pattern bundles
  // the state interface, initial-state constant, action implementations, and
  // the `create()` hook in one file; that's the unit of cohesion.
  // ---------------------------------------------------------------------------
  {
    files: ["src/**/*.store.ts"],
    rules: {
      "module-boundaries/single-semantic-module": "off"
    }
  },

  // ---------------------------------------------------------------------------
  // lib/env/* — sole readers of import.meta.env
  // (env-access plugin enforces the rest)
  // ---------------------------------------------------------------------------
  {
    files: ["src/lib/env/**/*.ts"],
    rules: {
      "env-access/no-direct-process-env": "off"
    }
  },

  // ---------------------------------------------------------------------------
  // HTTP transport + logger internals — the only places that may touch low-level
  // browser primitives directly.
  // ---------------------------------------------------------------------------
  {
    files: ["src/lib/api/openapi.ts"],
    rules: {
      "no-restricted-globals": "off",
      // HTTP transport composition root: middleware definitions + retry
      // state + the openapi-fetch client init are one natural unit.
      "module-boundaries/single-semantic-module": "off"
    }
  },
  {
    files: ["src/lib/logger/logger.ts", "src/lib/logger/logger.utils.ts"],
    rules: {
      "no-console": "off"
    }
  },
  {
    files: ["src/lib/time/**/*.ts"],
    rules: {
      "no-restricted-syntax": "off"
    }
  },
  /*
   * src/** (except generated ACL/OpenAPI artifacts and now.ts): date ban +
   * role-literal ban. Generated acl.types.generated.ts owns the literals;
   * tests/stories get a relaxed override below.
   */
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/lib/acl/acl.types.generated.ts",
      "src/lib/api/schema.d.ts",
      "src/lib/time/**/*.ts"
    ],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.type='MemberExpression'][callee.property.name='toISOString'][callee.object.type='NewExpression'][callee.object.callee.name='Date'][callee.object.arguments.length=0]",
          message:
            "Use now() from @/lib/time/now instead of new Date().toISOString()."
        },
        {
          selector:
            'Literal[value="owner"], Literal[value="admin"], Literal[value="member"], Literal[value="viewer"]',
          message:
            "Use ROLE.owner/admin/member/viewer from acl.types instead of raw role string literals."
        }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // Stories — relaxed (inline functions OK for demo purposes)
  // ---------------------------------------------------------------------------
  {
    files: ["src/**/*.stories.tsx", ".storybook/**/*.{ts,tsx}"],
    rules: {
      "react/jsx-no-bind": "off",
      "react-refresh/only-export-components": "off",
      "no-console": "off",
      "structured-logging/require-event-field": "off",
      "structured-logging/typed-event-names": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.type='MemberExpression'][callee.property.name='toISOString'][callee.object.type='NewExpression'][callee.object.callee.name='Date'][callee.object.arguments.length=0]",
          message:
            "Use now() from @/lib/time/now instead of new Date().toISOString()."
        }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // Tests & E2E — relaxed
  // ---------------------------------------------------------------------------
  {
    files: ["tests/**/*.{ts,tsx}", "src/**/*.test.{ts,tsx}", "e2e/**/*.ts"],
    rules: {
      "no-console": "off",
      "structured-logging/require-event-field": "off",
      "structured-logging/mask-pii-fields": "off",
      "structured-logging/typed-event-names": "off",
      "react-hooks/rules-of-hooks": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "react/jsx-no-bind": "off",
      "sonarjs/cognitive-complexity": "off",
      // Tests mix mocks, fixtures, helpers, and the test body itself; that's
      // the natural unit and shouldn't be split across files.
      "module-boundaries/single-semantic-module": "off",
      // Tests measure elapsed time, verify clock behaviour, and stamp
      // fixture timestamps — direct Date.now() / new Date() is the right
      // tool here. Production code routes through nowMs().
      "code-flow/no-bare-date-now": "off",
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.type='MemberExpression'][callee.property.name='toISOString'][callee.object.type='NewExpression'][callee.object.callee.name='Date'][callee.object.arguments.length=0]",
          message:
            "Use now() from @/lib/time/now instead of new Date().toISOString()."
        }
      ]
    }
  },

  // ---------------------------------------------------------------------------
  // Storybook stories — `meta` const + `IStory` type + named-export consts
  // is the universal Storybook shape; splitting into siblings would fight
  // the framework's convention and break HMR.
  // ---------------------------------------------------------------------------
  {
    files: ["src/**/*.stories.tsx"],
    rules: {
      "module-boundaries/single-semantic-module": "off"
    }
  },

  // ---------------------------------------------------------------------------
  // Playwright fixtures — empty destructuring is required by their API
  // ---------------------------------------------------------------------------
  // Playwright introspects the source of fixture functions to discover their
  // dependencies; the first argument MUST be an object destructuring pattern,
  // even when the fixture has no dependencies. Disabling no-empty-pattern is
  // the only correct path. Scoped narrowly to e2e/fixtures/ so accidental
  // empty patterns elsewhere still get caught.
  {
    files: ["e2e/fixtures/**/*.ts"],
    rules: {
      "no-empty-pattern": "off"
    }
  },

  // ---------------------------------------------------------------------------
  // Scripts & config files — relaxed (node-side tools)
  // ---------------------------------------------------------------------------
  {
    files: [
      "scripts/**/*.ts",
      "*.config.{ts,mts,mjs,js}",
      ".storybook/**/*.{ts,tsx}"
    ],
    rules: {
      "no-console": "off",
      "structured-logging/require-event-field": "off",
      "structured-logging/typed-event-names": "off",
      "env-access/no-direct-process-env": "off",
      "no-restricted-globals": "off",
      // Build / codegen scripts legitimately mix constants, helpers, and
      // a top-level main() driver in one file.
      "module-boundaries/single-semantic-module": "off"
    }
  },
  /*
   * no-raw-role-literals.ts defines the role-literal scanner: it must mention
   * "owner"|"admin"|… in patterns and Set literals. lint:meta enforces the
   * ban in src/**; ESLint skips this one meta-lint file only.
   */
  {
    files: ["scripts/lint-meta/rules/source-text/no-raw-role-literals.ts"],
    rules: {
      "no-restricted-syntax": "off"
    }
  }
);
