apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: boringstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-role
  namespace: boringstack
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["boringstack-secrets", "boringstack-db-app"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-rolebinding
  namespace: boringstack
subjects:
  - kind: ServiceAccount
    name: api
    namespace: boringstack
roleRef:
  kind: Role
  name: api-role
  apiGroup: rbac.authorization.k8s.io
