apiVersion: v1
kind: Service
metadata:
  name: glitchtip-web
  namespace: boringstack-prod
  labels:
    app: glitchtip
    component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: glitchtip
    component: web
