#!/usr/bin/env tsx
/**
 * Regenerate src/lib/api/schema.d.ts from the api-template's OpenAPI document.
 *
 *   pnpm generate:api            # writes the file in place
 *   pnpm generate:api:check      # exit 1 if regeneration would change the file
 *
 * URL comes from env (`OPENAPI_URL`, then `VITE_API_URL`, then localhost:3000).
 * The api-template's Elysia swagger plugin serves the JSON at /swagger/json.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

import { getErrorMessage } from "../../src/lib/errors/getErrorMessage";

const OUTPUT = resolve(process.cwd(), "src/lib/api/schema.d.ts");

function resolveOpenApiUrl(): string {
  const explicit = process.env.OPENAPI_URL;

  if (explicit !== undefined && explicit !== "") {
    return explicit;
  }

  const api = process.env.VITE_API_URL;

  if (api !== undefined && api !== "") {
    return `${api.replace(/\/$/, "")}/swagger/json`;
  }

  return "http://localhost:3000/swagger/json";
}

const URL_FROM_ENV = resolveOpenApiUrl();

const BANNER = `/**
 * OpenAPI schema — DO NOT EDIT BY HAND.
 *
 * Regenerated by \`pnpm generate:api\` from ${URL_FROM_ENV}
 */

`;

async function generate(): Promise<string> {
  const ast = await openapiTS(new URL(URL_FROM_ENV));

  return BANNER + astToString(ast);
}

/*
 * Strip the banner before drift comparison: the banner embeds the source
 * URL, which varies by environment (dev :3000, alt port for CI smoke,
 * staging URL, etc). Two regenerations that hit different URLs but the
 * same spec produce identical bodies but different banners — that is
 * not real drift and must not fail the check.
 */
const stripBanner = (source: string): string =>
  source.replace(/^\/\*\*[\s\S]*?\*\/\s*/, "").trimStart();

async function main(): Promise<void> {
  const isCheckMode = process.argv.includes("--check");

  console.log(`[generate:api] Fetching ${URL_FROM_ENV}`);

  let generated: string;

  try {
    generated = await generate();
  } catch (error) {
    console.error(`[generate:api] FAILED: ${getErrorMessage(error)}`);
    console.error(
      "[generate:api] Hint: start the api-template (pnpm dev in api-template/)" +
        " or set OPENAPI_URL to a reachable spec."
    );
    process.exit(1);
  }

  if (isCheckMode) {
    if (!existsSync(OUTPUT)) {
      console.error(
        `[generate:api:check] ${OUTPUT} does not exist — run \`pnpm generate:api\``
      );
      process.exit(1);
    }

    const current = readFileSync(OUTPUT, "utf8");

    if (stripBanner(current) !== stripBanner(generated)) {
      console.error(
        `[generate:api:check] ${OUTPUT} is stale — run \`pnpm generate:api\` and commit.`
      );
      process.exit(1);
    }

    console.log("[generate:api:check] Schema is up to date.");

    return;
  }

  writeFileSync(OUTPUT, generated, "utf8");
  console.log(`[generate:api] Wrote ${OUTPUT}`);
}

void main();
