/**
 * OpenAPI schema — DO NOT EDIT BY HAND.
 *
 * Regenerated by `pnpm generate:api` from http://localhost:3000/swagger/json
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root liveness ping */
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe (DB + Valkey + email when configured)
         * @description Returns 200 when all checks are 'ok' or 'degraded'; 503 when any 'down'.
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime feature and OAuth provider capabilities */
        get: operations["getApiV1Capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user. No account or session is issued; the user must click the verification email link to activate. */
        post: operations["postApiV1AuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["postApiV1AuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email + provision personal account. Issues session cookies on success. */
        post: operations["postApiV1AuthVerify-email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend verification email */
        post: operations["postApiV1AuthResend-verification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/__test/force-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** TEST ONLY — force-verify a user + provision account + issue session. Returns 404 unless NODE_ENV=test or E2E_TEST_ENDPOINTS_ENABLED=true. */
        post: operations["postApiV1Auth__testForce-verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: operations["postApiV1AuthForgot-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with token */
        post: operations["postApiV1AuthReset-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: operations["postApiV1AuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh the auth cookie using the refresh session */
        post: operations["postApiV1AuthRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start OAuth login (redirects to provider) */
        get: operations["getApiV1AuthOauthByProvider"];
        put?: never;
        post?: never;
        /** Disconnect an OAuth provider from the current user */
        delete: operations["deleteApiV1AuthOauthByProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback — exchanges code, sets auth cookie */
        get: operations["getApiV1AuthOauthByProviderCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password while authenticated */
        post: operations["postApiV1AuthChange-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Link an OAuth provider to the current user */
        get: operations["getApiV1AuthOauthByProviderLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user, active account, memberships, and resolved features */
        get: operations["getApiV1UsersMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user profile */
        patch: operations["patchApiV1UsersMe"];
        trace?: never;
    };
    "/api/v1/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available plans */
        get: operations["getApiV1BillingPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current account subscription */
        get: operations["getApiV1BillingSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/stripe/checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Stripe Checkout session */
        post: operations["postApiV1BillingStripeCheckout-session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/stripe/portal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Stripe Customer Portal session */
        post: operations["postApiV1BillingStripePortal-session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/stripe/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe webhook receiver */
        post: operations["postApiV1BillingStripeWebhooks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-queue job counts (admin only) */
        get: operations["getApiV1AdminQueues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard summary stats (per user) */
        get: operations["getApiV1DashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent activity feed for the current user */
        get: operations["getApiV1DashboardActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a Web Push subscription for the current user */
        post: operations["postApiV1NotificationsPushSubscribe"];
        /** Remove a Web Push subscription for the current user */
        delete: operations["deleteApiV1NotificationsPushSubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's Web Push subscriptions */
        get: operations["getApiV1NotificationsPushSubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's notifications */
        get: operations["getApiV1Notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's notification preferences */
        get: operations["getApiV1NotificationsPreferences"];
        /** Bulk-update notification preferences */
        put: operations["putApiV1NotificationsPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark a notification as read or archived */
        patch: operations["patchApiV1NotificationsById"];
        trace?: never;
    };
    "/api/v1/notifications/mark-all-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark every unread notification as read */
        post: operations["postApiV1NotificationsMark-all-read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-Sent Events stream of new notifications */
        get: operations["getApiV1NotificationsStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/widgets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List widgets in the active account */
        get: operations["getApiV1Widgets"];
        put?: never;
        /** Create a widget in the active account */
        post: operations["postApiV1Widgets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/widgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a widget by id (account-scoped) */
        get: operations["getApiV1WidgetsById"];
        put?: never;
        post?: never;
        /** Delete a widget (account-scoped) */
        delete: operations["deleteApiV1WidgetsById"];
        options?: never;
        head?: never;
        /** Update a widget (account-scoped) */
        patch: operations["patchApiV1WidgetsById"];
        trace?: never;
    };
    "/api/v1/accounts/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch the active account for this session */
        post: operations["postApiV1AccountsSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending (not accepted, not revoked) invitations */
        get: operations["getApiV1AccountsByIdInvitations"];
        put?: never;
        /** Invite a teammate to an account */
        post: operations["postApiV1AccountsByIdInvitations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/invitations/{invitationId}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend (and rotate) an invitation token */
        post: operations["postApiV1AccountsByIdInvitationsByInvitationIdResend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete the account (30-day grace + background hard-delete) */
        delete: operations["deleteApiV1AccountsById"];
        options?: never;
        head?: never;
        /** Rename the active account */
        patch: operations["patchApiV1AccountsById"];
        trace?: never;
    };
    "/api/v1/accounts/{id}/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer ownership of an account to another member */
        post: operations["postApiV1AccountsByIdTransfer-ownership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an invitation */
        delete: operations["deleteApiV1AccountsByIdInvitationsByInvitationId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invitation by its raw token */
        post: operations["postApiV1InvitationsAccept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getApiV1Capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        features: {
                            notifications: {
                                sse: boolean;
                                webPush: boolean;
                            };
                            billing: {
                                enabled: boolean;
                            };
                            ai: {
                                enabled: boolean;
                            };
                        };
                        oauth: {
                            providers: ("google" | "github" | "linkedin")[];
                        };
                    };
                    "multipart/form-data": {
                        features: {
                            notifications: {
                                sse: boolean;
                                webPush: boolean;
                            };
                            billing: {
                                enabled: boolean;
                            };
                            ai: {
                                enabled: boolean;
                            };
                        };
                        oauth: {
                            providers: ("google" | "github" | "linkedin")[];
                        };
                    };
                    "text/plain": {
                        features: {
                            notifications: {
                                sse: boolean;
                                webPush: boolean;
                            };
                            billing: {
                                enabled: boolean;
                            };
                            ai: {
                                enabled: boolean;
                            };
                        };
                        oauth: {
                            providers: ("google" | "github" | "linkedin")[];
                        };
                    };
                };
            };
        };
    };
    postApiV1AuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    firstName?: string;
                    lastName?: string;
                };
                "multipart/form-data": {
                    /** Format: email */
                    email: string;
                    password: string;
                    firstName?: string;
                    lastName?: string;
                };
                "text/plain": {
                    /** Format: email */
                    email: string;
                    password: string;
                    firstName?: string;
                    lastName?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    postApiV1AuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
                "multipart/form-data": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
                "text/plain": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            user: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                emailVerified: boolean;
                            };
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            user: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                emailVerified: boolean;
                            };
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            user: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                emailVerified: boolean;
                            };
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    "postApiV1AuthVerify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
                "multipart/form-data": {
                    token: string;
                };
                "text/plain": {
                    token: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            user: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                emailVerified: boolean;
                            };
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            user: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                emailVerified: boolean;
                            };
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            user: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                emailVerified: boolean;
                            };
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    "postApiV1AuthResend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
                "multipart/form-data": {
                    /** Format: email */
                    email: string;
                };
                "text/plain": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    "postApiV1Auth__testForce-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
                "multipart/form-data": {
                    /** Format: email */
                    email: string;
                };
                "text/plain": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "postApiV1AuthForgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
                "multipart/form-data": {
                    /** Format: email */
                    email: string;
                };
                "text/plain": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    "postApiV1AuthReset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    password: string;
                };
                "multipart/form-data": {
                    token: string;
                    password: string;
                };
                "text/plain": {
                    token: string;
                    password: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    postApiV1AuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    postApiV1AuthRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            user: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                emailVerified: boolean;
                            };
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            user: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                emailVerified: boolean;
                            };
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            user: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                emailVerified: boolean;
                            };
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    getApiV1AuthOauthByProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteApiV1AuthOauthByProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    getApiV1AuthOauthByProviderCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "postApiV1AuthChange-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    currentPassword: string;
                    newPassword: string;
                };
                "multipart/form-data": {
                    currentPassword: string;
                    newPassword: string;
                };
                "text/plain": {
                    currentPassword: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            message: string;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    getApiV1AuthOauthByProviderLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getApiV1UsersMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            id: string;
                            email: string;
                            firstName: string;
                            lastName: string;
                            emailVerified: boolean;
                            createdAt: string;
                            updatedAt: string;
                        };
                        account: {
                            id: string;
                            name: string;
                        };
                        role: "owner" | "admin" | "member" | "viewer";
                        memberships: {
                            accountId: string;
                            accountName: string;
                            role: "owner" | "admin" | "member" | "viewer";
                        }[];
                        features: {
                            can_export: boolean;
                            can_invite_team: boolean;
                            max_seats: number;
                            max_widgets: number;
                        };
                        capabilities: {
                            billing: boolean;
                            notificationsSse: boolean;
                            webPush: boolean;
                        };
                        authProviders: string[];
                        hasPasswordLogin: boolean;
                    };
                    "multipart/form-data": {
                        user: {
                            id: string;
                            email: string;
                            firstName: string;
                            lastName: string;
                            emailVerified: boolean;
                            createdAt: string;
                            updatedAt: string;
                        };
                        account: {
                            id: string;
                            name: string;
                        };
                        role: "owner" | "admin" | "member" | "viewer";
                        memberships: {
                            accountId: string;
                            accountName: string;
                            role: "owner" | "admin" | "member" | "viewer";
                        }[];
                        features: {
                            can_export: boolean;
                            can_invite_team: boolean;
                            max_seats: number;
                            max_widgets: number;
                        };
                        capabilities: {
                            billing: boolean;
                            notificationsSse: boolean;
                            webPush: boolean;
                        };
                        authProviders: string[];
                        hasPasswordLogin: boolean;
                    };
                    "text/plain": {
                        user: {
                            id: string;
                            email: string;
                            firstName: string;
                            lastName: string;
                            emailVerified: boolean;
                            createdAt: string;
                            updatedAt: string;
                        };
                        account: {
                            id: string;
                            name: string;
                        };
                        role: "owner" | "admin" | "member" | "viewer";
                        memberships: {
                            accountId: string;
                            accountName: string;
                            role: "owner" | "admin" | "member" | "viewer";
                        }[];
                        features: {
                            can_export: boolean;
                            can_invite_team: boolean;
                            max_seats: number;
                            max_widgets: number;
                        };
                        capabilities: {
                            billing: boolean;
                            notificationsSse: boolean;
                            webPush: boolean;
                        };
                        authProviders: string[];
                        hasPasswordLogin: boolean;
                    };
                };
            };
        };
    };
    patchApiV1UsersMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    firstName?: string;
                    lastName?: string;
                };
                "multipart/form-data": {
                    firstName?: string;
                    lastName?: string;
                };
                "text/plain": {
                    firstName?: string;
                    lastName?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        email: string;
                        firstName: string;
                        lastName: string;
                        emailVerified: boolean;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        email: string;
                        firstName: string;
                        lastName: string;
                        emailVerified: boolean;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "text/plain": {
                        id: string;
                        email: string;
                        firstName: string;
                        lastName: string;
                        emailVerified: boolean;
                        createdAt: string;
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getApiV1BillingPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                        isDefault: boolean;
                    }[];
                    "multipart/form-data": {
                        id: number;
                        name: string;
                        isDefault: boolean;
                    }[];
                    "text/plain": {
                        id: number;
                        name: string;
                        isDefault: boolean;
                    }[];
                };
            };
        };
    };
    getApiV1BillingSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        planId: number;
                        planName: string;
                        isDefault: boolean;
                        status: string;
                        hasStripeSubscription: boolean;
                    };
                    "multipart/form-data": {
                        planId: number;
                        planName: string;
                        isDefault: boolean;
                        status: string;
                        hasStripeSubscription: boolean;
                    };
                    "text/plain": {
                        planId: number;
                        planName: string;
                        isDefault: boolean;
                        status: string;
                        hasStripeSubscription: boolean;
                    };
                };
            };
        };
    };
    "postApiV1BillingStripeCheckout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    planId: number;
                    /** Format: uri */
                    successUrl: string;
                    /** Format: uri */
                    cancelUrl: string;
                };
                "multipart/form-data": {
                    planId: number;
                    /** Format: uri */
                    successUrl: string;
                    /** Format: uri */
                    cancelUrl: string;
                };
                "text/plain": {
                    planId: number;
                    /** Format: uri */
                    successUrl: string;
                    /** Format: uri */
                    cancelUrl: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url: string;
                    };
                    "multipart/form-data": {
                        url: string;
                    };
                    "text/plain": {
                        url: string;
                    };
                };
            };
        };
    };
    "postApiV1BillingStripePortal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    returnUrl: string;
                };
                "multipart/form-data": {
                    /** Format: uri */
                    returnUrl: string;
                };
                "text/plain": {
                    /** Format: uri */
                    returnUrl: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url: string;
                    };
                    "multipart/form-data": {
                        url: string;
                    };
                    "text/plain": {
                        url: string;
                    };
                };
            };
        };
    };
    postApiV1BillingStripeWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            received: boolean;
                            type: string;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            received: boolean;
                            type: string;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            received: boolean;
                            type: string;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    getApiV1AdminQueues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        queues: {
                            name: string;
                            counts: {
                                waiting: number;
                                active: number;
                                completed: number;
                                failed: number;
                                delayed: number;
                                paused: number;
                            };
                        }[];
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        queues: {
                            name: string;
                            counts: {
                                waiting: number;
                                active: number;
                                completed: number;
                                failed: number;
                                delayed: number;
                                paused: number;
                            };
                        }[];
                        timestamp: string;
                    };
                    "text/plain": {
                        queues: {
                            name: string;
                            counts: {
                                waiting: number;
                                active: number;
                                completed: number;
                                failed: number;
                                delayed: number;
                                paused: number;
                            };
                        }[];
                        timestamp: string;
                    };
                };
            };
        };
    };
    getApiV1DashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        totalEvents: number;
                        recentActivity: {
                            id: string;
                            title: string;
                            timestamp: string;
                        }[];
                    };
                    "multipart/form-data": {
                        totalEvents: number;
                        recentActivity: {
                            id: string;
                            title: string;
                            timestamp: string;
                        }[];
                    };
                    "text/plain": {
                        totalEvents: number;
                        recentActivity: {
                            id: string;
                            title: string;
                            timestamp: string;
                        }[];
                    };
                };
            };
        };
    };
    getApiV1DashboardActivity: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            title: string;
                            timestamp: string;
                        }[];
                        nextCursor: string | null;
                    };
                    "multipart/form-data": {
                        items: {
                            id: string;
                            title: string;
                            timestamp: string;
                        }[];
                        nextCursor: string | null;
                    };
                    "text/plain": {
                        items: {
                            id: string;
                            title: string;
                            timestamp: string;
                        }[];
                        nextCursor: string | null;
                    };
                };
            };
        };
    };
    postApiV1NotificationsPushSubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    endpoint: string;
                    keys: {
                        p256dh: string;
                        auth: string;
                    };
                    expirationTime?: number | null;
                    userAgent?: string;
                };
                "multipart/form-data": {
                    endpoint: string;
                    keys: {
                        p256dh: string;
                        auth: string;
                    };
                    expirationTime?: number | null;
                    userAgent?: string;
                };
                "text/plain": {
                    endpoint: string;
                    keys: {
                        p256dh: string;
                        auth: string;
                    };
                    expirationTime?: number | null;
                    userAgent?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: {
                            id: string;
                            endpoint: string;
                            userAgent: string | null;
                            createdAt: string;
                            lastUsedAt: string;
                        };
                    };
                    "multipart/form-data": {
                        subscription: {
                            id: string;
                            endpoint: string;
                            userAgent: string | null;
                            createdAt: string;
                            lastUsedAt: string;
                        };
                    };
                    "text/plain": {
                        subscription: {
                            id: string;
                            endpoint: string;
                            userAgent: string | null;
                            createdAt: string;
                            lastUsedAt: string;
                        };
                    };
                };
            };
        };
    };
    deleteApiV1NotificationsPushSubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    endpoint: string;
                };
                "multipart/form-data": {
                    endpoint: string;
                };
                "text/plain": {
                    endpoint: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        removed: number;
                    };
                    "multipart/form-data": {
                        removed: number;
                    };
                    "text/plain": {
                        removed: number;
                    };
                };
            };
        };
    };
    getApiV1NotificationsPushSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            endpoint: string;
                            userAgent: string | null;
                            createdAt: string;
                            lastUsedAt: string;
                        }[];
                    };
                    "multipart/form-data": {
                        items: {
                            id: string;
                            endpoint: string;
                            userAgent: string | null;
                            createdAt: string;
                            lastUsedAt: string;
                        }[];
                    };
                    "text/plain": {
                        items: {
                            id: string;
                            endpoint: string;
                            userAgent: string | null;
                            createdAt: string;
                            lastUsedAt: string;
                        }[];
                    };
                };
            };
        };
    };
    getApiV1Notifications: {
        parameters: {
            query?: {
                status?: "unread" | "read" | "archived";
                limit?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            eventType: string;
                            title: string;
                            body: string;
                            ctaUrl: string | null;
                            ctaLabel: string | null;
                            status: "unread" | "read" | "archived";
                            readAt: string | null;
                            createdAt: string;
                        }[];
                        nextCursor: string | null;
                    };
                    "multipart/form-data": {
                        items: {
                            id: string;
                            eventType: string;
                            title: string;
                            body: string;
                            ctaUrl: string | null;
                            ctaLabel: string | null;
                            status: "unread" | "read" | "archived";
                            readAt: string | null;
                            createdAt: string;
                        }[];
                        nextCursor: string | null;
                    };
                    "text/plain": {
                        items: {
                            id: string;
                            eventType: string;
                            title: string;
                            body: string;
                            ctaUrl: string | null;
                            ctaLabel: string | null;
                            status: "unread" | "read" | "archived";
                            readAt: string | null;
                            createdAt: string;
                        }[];
                        nextCursor: string | null;
                    };
                };
            };
        };
    };
    getApiV1NotificationsPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            eventType: string;
                            channel: string;
                            enabled: boolean;
                        }[];
                    };
                    "multipart/form-data": {
                        items: {
                            eventType: string;
                            channel: string;
                            enabled: boolean;
                        }[];
                    };
                    "text/plain": {
                        items: {
                            eventType: string;
                            channel: string;
                            enabled: boolean;
                        }[];
                    };
                };
            };
        };
    };
    putApiV1NotificationsPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    preferences: {
                        eventType: string;
                        channel: string;
                        enabled: boolean;
                    }[];
                };
                "multipart/form-data": {
                    preferences: {
                        eventType: string;
                        channel: string;
                        enabled: boolean;
                    }[];
                };
                "text/plain": {
                    preferences: {
                        eventType: string;
                        channel: string;
                        enabled: boolean;
                    }[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            eventType: string;
                            channel: string;
                            enabled: boolean;
                        }[];
                    };
                    "multipart/form-data": {
                        items: {
                            eventType: string;
                            channel: string;
                            enabled: boolean;
                        }[];
                    };
                    "text/plain": {
                        items: {
                            eventType: string;
                            channel: string;
                            enabled: boolean;
                        }[];
                    };
                };
            };
        };
    };
    patchApiV1NotificationsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: "read" | "archived";
                };
                "multipart/form-data": {
                    status: "read" | "archived";
                };
                "text/plain": {
                    status: "read" | "archived";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        eventType: string;
                        title: string;
                        body: string;
                        ctaUrl: string | null;
                        ctaLabel: string | null;
                        status: "unread" | "read" | "archived";
                        readAt: string | null;
                        createdAt: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        eventType: string;
                        title: string;
                        body: string;
                        ctaUrl: string | null;
                        ctaLabel: string | null;
                        status: "unread" | "read" | "archived";
                        readAt: string | null;
                        createdAt: string;
                    };
                    "text/plain": {
                        id: string;
                        eventType: string;
                        title: string;
                        body: string;
                        ctaUrl: string | null;
                        ctaLabel: string | null;
                        status: "unread" | "read" | "archived";
                        readAt: string | null;
                        createdAt: string;
                    };
                };
            };
        };
    };
    "postApiV1NotificationsMark-all-read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        updated: number;
                    };
                    "multipart/form-data": {
                        updated: number;
                    };
                    "text/plain": {
                        updated: number;
                    };
                };
            };
        };
    };
    getApiV1NotificationsStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getApiV1Widgets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            accountId: string;
                            name: string;
                            createdAt: string;
                            updatedAt: string;
                        }[];
                    };
                    "multipart/form-data": {
                        items: {
                            id: string;
                            accountId: string;
                            name: string;
                            createdAt: string;
                            updatedAt: string;
                        }[];
                    };
                    "text/plain": {
                        items: {
                            id: string;
                            accountId: string;
                            name: string;
                            createdAt: string;
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
    };
    postApiV1Widgets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
                "multipart/form-data": {
                    name: string;
                };
                "text/plain": {
                    name: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        accountId: string;
                        name: string;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        accountId: string;
                        name: string;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "text/plain": {
                        id: string;
                        accountId: string;
                        name: string;
                        createdAt: string;
                        updatedAt: string;
                    };
                };
            };
        };
    };
    getApiV1WidgetsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        accountId: string;
                        name: string;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        accountId: string;
                        name: string;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "text/plain": {
                        id: string;
                        accountId: string;
                        name: string;
                        createdAt: string;
                        updatedAt: string;
                    };
                };
            };
        };
    };
    deleteApiV1WidgetsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchApiV1WidgetsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
                "multipart/form-data": {
                    name: string;
                };
                "text/plain": {
                    name: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        accountId: string;
                        name: string;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        accountId: string;
                        name: string;
                        createdAt: string;
                        updatedAt: string;
                    };
                    "text/plain": {
                        id: string;
                        accountId: string;
                        name: string;
                        createdAt: string;
                        updatedAt: string;
                    };
                };
            };
        };
    };
    postApiV1AccountsSwitch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    accountId: string;
                };
                "multipart/form-data": {
                    /** Format: uuid */
                    accountId: string;
                };
                "text/plain": {
                    /** Format: uuid */
                    accountId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            accountId: string;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            accountId: string;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            accountId: string;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    getApiV1AccountsByIdInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        accountId: string;
                        email: string;
                        roleToAssign: string;
                        expiresAt: string;
                    }[];
                    "multipart/form-data": {
                        id: string;
                        accountId: string;
                        email: string;
                        roleToAssign: string;
                        expiresAt: string;
                    }[];
                    "text/plain": {
                        id: string;
                        accountId: string;
                        email: string;
                        roleToAssign: string;
                        expiresAt: string;
                    }[];
                };
            };
        };
    };
    postApiV1AccountsByIdInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    roleToAssign: "admin" | "member" | "viewer";
                };
                "multipart/form-data": {
                    /** Format: email */
                    email: string;
                    roleToAssign: "admin" | "member" | "viewer";
                };
                "text/plain": {
                    /** Format: email */
                    email: string;
                    roleToAssign: "admin" | "member" | "viewer";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        accountId: string;
                        email: string;
                        roleToAssign: string;
                        expiresAt: string;
                        rawToken?: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        accountId: string;
                        email: string;
                        roleToAssign: string;
                        expiresAt: string;
                        rawToken?: string;
                    };
                    "text/plain": {
                        id: string;
                        accountId: string;
                        email: string;
                        roleToAssign: string;
                        expiresAt: string;
                        rawToken?: string;
                    };
                };
            };
        };
    };
    postApiV1AccountsByIdInvitationsByInvitationIdResend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        accountId: string;
                        email: string;
                        roleToAssign: string;
                        expiresAt: string;
                        rawToken?: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        accountId: string;
                        email: string;
                        roleToAssign: string;
                        expiresAt: string;
                        rawToken?: string;
                    };
                    "text/plain": {
                        id: string;
                        accountId: string;
                        email: string;
                        roleToAssign: string;
                        expiresAt: string;
                        rawToken?: string;
                    };
                };
            };
        };
    };
    deleteApiV1AccountsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchApiV1AccountsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
                "multipart/form-data": {
                    name: string;
                };
                "text/plain": {
                    name: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                    };
                    "multipart/form-data": {
                        id: string;
                        name: string;
                    };
                    "text/plain": {
                        id: string;
                        name: string;
                    };
                };
            };
        };
    };
    "postApiV1AccountsByIdTransfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    toUserId: string;
                };
                "multipart/form-data": {
                    /** Format: uuid */
                    toUserId: string;
                };
                "text/plain": {
                    /** Format: uuid */
                    toUserId: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            transferred: boolean;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            transferred: boolean;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            transferred: boolean;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
    deleteApiV1AccountsByIdInvitationsByInvitationId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postApiV1InvitationsAccept: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
                "multipart/form-data": {
                    token: string;
                };
                "text/plain": {
                    token: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: {
                            accepted: boolean;
                        };
                        timestamp: string;
                    };
                    "multipart/form-data": {
                        success: boolean;
                        data: {
                            accepted: boolean;
                        };
                        timestamp: string;
                    };
                    "text/plain": {
                        success: boolean;
                        data: {
                            accepted: boolean;
                        };
                        timestamp: string;
                    };
                };
            };
        };
    };
}
